---
# Config file for automatic testing at travis-ci.org
language: python

jobs:
  include:
    - name: "Python 3.7 on Windows"
      os: windows
      language: generic
      python: 3.7
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7

# install package + test dependencies
install:
  - pip install ".[test]" .

# run tests
script: pytest

# perform coverage
after_success:
  - codecov
