---
# Config file for automatic testing at travis-ci.org

language: minimal

os: osx

# -- build --------------------------------------

matrix:
  # bail-out early for failures
  fast_finish: true

  include:
    # conda builds
    - name: "conda:3.6"
      env: PYTHON_VERSION="3.6"
    - name: "conda:3.7"
      env: PYTHON_VERSION="3.7"
    - name: "conda:3.8"
      env: PYTHON_VERSION="3.8"

install:
  - set -ex;
  # install miniconda, create env, and activate
  - . ./ci/install-conda.sh
  # install this package
  - python -m pip install .

# run tests
script: pytest

# perform coverage
after_success:
  - codecov
