---
# Config file for automatic testing at travis-ci.org
language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov


# install package + test dependencies
install:
  - pip install ".[test]" .

# run tests
script: pytest

# perform coverage
after_success:
  - codecov
